name: release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Set variables
        id: vars
        run: |
          echo ::set-output name=version_tag::$(echo ${GITHUB_REF#refs/*/})
          echo ::set-output name=repo_name::$(echo ${GITHUB_REPOSITORY#*/*})

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./buildkit.Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:${{ steps.vars.outputs.version_tag }}
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.version_tag }}
          build-args: |
            APP_HOME=/home/node/${{ steps.vars.outputs.repo_name }}
          cache-from: |
            ${{ github.repository }}:latest
