name: release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./buildkit.Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:${GITHUB_REF#refs/*/}
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${GITHUB_REF#refs/*/}
          build-args: |
            APP_HOME=/home/node/${GITHUB_REPOSITORY#octocat/*}
          cache-from: |
            ${{ github.repository }}:latest
