name: release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Build image
        run: docker build . --file buildkit.Dockerfile --tag ${{ github.repository }}

      - name: Push latest image (hub)
        run: docker push ${{ github.repository }}:latest

      - name: Tag versioned image (hub)
        run: docker tag ${{ github.repository }}:latest ${{ github.repository }}:${GITHUB_REF#refs/*/}

      - name: Push versioned image (hub)
        run: docker push ${{ github.repository }}:${GITHUB_REF#refs/*/}

      - name: Tag latest image (gh-cr)
        run: docker tag ${{ github.repository }}:latest ghcr.io/${{ github.repository }}

      - name: Push latest image (gh-cr)
        run: docker push ${{ github.repository }}:latest

      - name: Tag versioned image (gh-cr)
        run: docker tag ${{ github.repository }}:latest ghcr.io/${{ github.repository }}:${GITHUB_REF#refs/*/}

      - name: Push versioned image (gh-cr)
        run: docker push ${{ github.repository }}:${GITHUB_REF#refs/*/}
